name: iot_ph
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get_storage: ^2.1.1
  get: 4.6.6
  flutter: 
    sdk: flutter
  intl: ^0.19.0
  firebase_database: ^10.4.3
  firebase_core: ^2.25.2
  excel: ^4.0.2
  path_provider: ^2.1.2
  permission_handler: ^11.2.0
  open_file_plus: ^3.4.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/image/
  uses-material-design: true

